version: '3.4'
services:
#  authentication:
#    build:
#      context: ../authentication
#      dockerfile: Dockerfile
#    environment:
#      TRANSACTION_SERVICE_URL: ${TRANSACTION_SERVICE_URL}
#    depends_on:
#      - transaction
#    restart: always

  transaction-database:
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: transactionsdb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always

  transaction:
    build:
      context: ../transaction
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - transaction-database
    restart: always
