version: '3.4'
services:
  authentication:
    build:
      context: ../authentication
      dockerfile: Dockerfile
    environment:
      TRANSACTION_SERVICE_URL: http://transaction:8080/transactions
    ports:
      - 8081:8081
    depends_on:
      - transaction
    restart: always

  transaction-database:
    image: postgres:17.4
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - type: volume
        source: transaction_database_data
        target: /var/lib/postgresql/data
    ports:
      - 5432:${PSQL_DATABASE_PORT}
    restart: always

  transaction:
    build:
      context: ../transaction
      dockerfile: Dockerfile
    environment:
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DATABASE_HOST: transaction-database
      PSQL_DATABASE_PORT: ${PSQL_DATABASE_PORT}
    ports:
      - 8080:8080
    depends_on:
      - transaction-database
    restart: always

volumes:
  transaction_database_data:
